#!/usr/bin/env ruby

# Tag both semver and ruby format version

ver = ARGV[0] || begin
  require File.expand_path('../lib/bootstrap-sass/version.rb', File.dirname(__FILE__))
  Bootstrap::VERSION
end

ver = "v#{ver}" unless ver.start_with?('v')
sem_ver = ver.reverse.split('.', 2).join('-').reverse

system <<-SH
set -x
git tag -a -m #{ver} #{ver}
git tag -a -m #{sem_ver} #{sem_ver}
SH
